package com.ti4n.freechat.model.response.freechat

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class ERC20Token(
    val Abi: String,
    val Address: String,
    val ChainID: Int,
    val Decimals: Int,
    val LogoURI: String,
    val Name: String,
    val bitcointalk: String,
    val blog: String,
    val blueCheckmark: String,
    val contractAddress: String,
    val description: String,
    val discord: String,
    val divisor: String,
    val email: String,
    val facebook: String,
    val github: String,
    val linkedin: String,
    val reddit: String,
    val slack: String,
    val symbol: String,
    val telegram: String,
    val tokenName: String,
    val tokenPriceUSD: String,
    val tokenType: String,
    val totalSupply: String,
    val twitter: String,
    val website: String,
    val wechat: String,
    val whitepaper: String,
) : Parcelable

@Parcelize
data class ERC20Tokens(val result: List<ERC20Token>) : Parcelable

val ethereum = ERC20Token(
    Abi = "",
    Address = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    ChainID = 0,
    Decimals = 18,
    LogoURI = "https://tokens.1inch.io/0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.png",
    Name = "Ethereum",
    bitcointalk = "",
    blog = "",
    blueCheckmark = "",
    contractAddress = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    description = "",
    discord = "",
    divisor = "",
    email = "",
    facebook = "",
    github = "",
    linkedin = "",
    reddit = "",
    slack = "",
    symbol = "ETH",
    telegram = "",
    tokenName = "",
    tokenPriceUSD = "",
    tokenType = "",
    totalSupply = "",
    twitter = "",
    website = "",
    wechat = "",
    whitepaper = "",
)

val wethereum = ERC20Token(
    Abi = "",
    Address = "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
    ChainID = 0,
    Decimals = 18,
    LogoURI = "https://tokens.1inch.io/0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.png",
    Name = "Wrapped Ether",
    bitcointalk = "",
    blog = "",
    blueCheckmark = "",
    contractAddress = "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
    description = "",
    discord = "",
    divisor = "",
    email = "",
    facebook = "",
    github = "",
    linkedin = "",
    reddit = "",
    slack = "",
    symbol = "WETH",
    telegram = "",
    tokenName = "",
    tokenPriceUSD = "",
    tokenType = "",
    totalSupply = "",
    twitter = "",
    website = "",
    wechat = "",
    whitepaper = "",
)